### ISSUE TITLE
Problem deploying with Github actions

### ISSUE THREAD

**Issue by patbranchaud** [jthegedus/svelte-adapter-firebase#211]
### Describe the Bug

Hey,

maybe you can help, but I know it's not directly related to your script but I'm not sure were to start.
I have a sveltkit / tailwindcss / github / firebase app that I am trying to put make work
and I'm using the svelte-adapter-firebase

Problem is
- When I build locally `npm run build` and deploy `firebase deploy` online from my computer I works perfectly fine
- When I build and deploy using github action yml trigerred on merge the app is broken. 
I'm getting multiple 404 : 
<img width="497" alt="Capture d’écran, le 2023-04-05 à 09 45 04" src="https://user-images.githubusercontent.com/79772987/230099478-bd34dd6b-c621-46a7-b03a-619c6b8c5925.png">

It's like some of the app files is still referring to the files created by the build I've done locally.
They are not replaced by the new files
Could it be because the github action is not updating the ssr function?

Can you point me in the right direction to fix this?
Let me know if I'm not clear.

Thank you!

### Steps to Reproduce

```
// import adapter from '@sveltejs/adapter-auto';
import firebase from 'svelte-adapter-firebase';
import { vitePreprocess } from '@sveltejs/kit/vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: firebase()
	},
	preprocess: vitePreprocess()
};

export default config;
```

```
# The github action file :
name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - run: npm run build
      - name: Check build output
        run: ls -la build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.MY_GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.MY_FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: myprojectId
```

### Expected Behaviour

no 404

### svelte-adapter-firebase version

^0.15.0

### sveltejs/kit version

^1.0.0-next.587
